-- EX1: RETORNANDO COLUNAS INDIVIDUAIS
SELECT
    prod_name
FROM
    Products;
    
-- EX2: MULTIPLAS COLUNAS
SELECT
    prod_id,
    prod_name,
    prod_price
FROM
    Products;
    
-- EX3: TODAS AS COLUNAS
SELECT
    * -- WILDCARD COMUM EM VARIAS LINGUAGENS
FROM
    Products;
    
-- EX4: COLUNAS DISTINTAS (EXCLUI REPETICOES)
SELECT DISTINCT
    vend_id
FROM
    Products;
    
-- EX5: LIMITAR RESULTADOS
SELECT 
    prod_name
FROM
    Products
LIMIT 5; -- O NUMERAL REPRESENTA A QTD DE COLUNAS A SEREM MOSTRADAS

-- EX5: LIMITAR RESULTADOS PARTINDO DE UMA COLUNA
SELECT 
    prod_name
FROM
    Products
LIMIT 5 OFFSET 2; -- OFFSET: DE QUAL COLUNA DEVE COMEÇAR A EXIBIR (EXCLUINDO AS QUE VIEREM ANTES)