-- 1:
SELECT -- ESCOLHA OS DADOS A SEREM EXIBIDOS
    cust_id -- COLUNA ESCOLHIDA
FROM -- ESCOLHA DE ONDE OS DADOS SERÃO RETIRADOS
    Customers; -- TABELA ESCOLHIDA

-- 2:
SELECT DISTINCT -- RETORNA VALORES SEM REPETIÇÕES
    prod_id 
FROM
    OrderItems;

-- 3:
SELECT 
    * -- WILDCARD: TODOS OS DADOS
FROM 
    Customers;

-- 3:
SELECT 
    cust_id
FROM 
    Customers;

